server:
  port: 7051

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false