
server:
  port: 8888 # 端口: 8080
spring:
  gobrs:
    async:
      rules:
        - name: "test"
          content: "AService->BService->CService,FService->HService"
        #        - name: "azh"
        #          content: "AService->BService,CService,FService; BService->FService,GService;"
        - name: "aiirs"
          content: "AService->BService,CService->DService; FService->FService,GService;"
      task-interrupt: false #局部异常是否打断主流程